title: The White Hat
description: A Cyber Security Blog 
url: https://h4ck1t.github.io/thewhitehat
baseurl: /thewhitehat
author: H4ck1t
future: false
source: .
destination: ./_site
layouts_dir: _layouts
markdown_ext: md
plugins: [jekyll-sitemap , jekyll-seo-tag]
