name: The White Hat

autho: H4ck1t

future: true

source: .

destination: ./_site

layouts_dir: _layouts

markdown_ext: md

plugins: [jekyll-paginate , jekyll-sitemap]

paginate: 6

paginate_path: "/blog/page:num/"
