title: The White Hat
description: A Cyber Security Blog 
url: https://thewhiteh4t.github.io
baseurl: 
author: thewhiteh4t
layouts_dir: _layouts
plugins: 
  - jekyll-sitemap 
  - jekyll-seo-tag
  - jekyll-paginate
