title: thewhiteh4t
description: The Best Offense is a Great Defense 
url: //thewhiteh4t.github.io
baseurl: 
author: thewhiteh4t
layouts_dir: _layouts
plugins: 
  - jekyll-sitemap 
  - jekyll-seo-tag
  - jekyll-paginate
